[package]
name = "yeet"
version = "0.1.0"
edition = "2021"
default-run = "yeet"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.18", default-features = false, features = [ "3d", "bevy_camera_controller", "free_camera" ] }
bevy-inspector-egui = "*"
avian3d = { version = "0.6.0-rc.1", features = [
    "simd",
    "diagnostic_ui",
    "collider-from-mesh",
    "bevy_scene",
    "serialize",
    "debug-plugin"
] }
bevy_ahoy = "0.1.0-rc.6"
bevy_enhanced_input = "0.24"
bevy_skein = "0.5"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

# Suggested by bevy-rapier
[profile.release]
codegen-units = 1

